// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentDataReporting;

#nullable disable

namespace StudentDataReporting.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250610143334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentDataReporting.Data.Marks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 85,
                            StudentId = 1,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Score = 90,
                            StudentId = 2,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 3,
                            Score = 78,
                            StudentId = 3,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 4,
                            Score = 92,
                            StudentId = 4,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 5,
                            Score = 88,
                            StudentId = 5,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 6,
                            Score = 76,
                            StudentId = 6,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 7,
                            Score = 80,
                            StudentId = 7,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 8,
                            Score = 95,
                            StudentId = 8,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 9,
                            Score = 91,
                            StudentId = 9,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 10,
                            Score = 84,
                            StudentId = 10,
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 11,
                            Score = 89,
                            StudentId = 1,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 12,
                            Score = 95,
                            StudentId = 2,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 13,
                            Score = 76,
                            StudentId = 3,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 14,
                            Score = 92,
                            StudentId = 4,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 15,
                            Score = 82,
                            StudentId = 5,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 16,
                            Score = 50,
                            StudentId = 6,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 17,
                            Score = 45,
                            StudentId = 7,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 18,
                            Score = 71,
                            StudentId = 8,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 19,
                            Score = 100,
                            StudentId = 9,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 20,
                            Score = 60,
                            StudentId = 10,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 21,
                            Score = 55,
                            StudentId = 1,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 22,
                            Score = 58,
                            StudentId = 2,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 23,
                            Score = 62,
                            StudentId = 3,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 24,
                            Score = 70,
                            StudentId = 4,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 25,
                            Score = 66,
                            StudentId = 5,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 26,
                            Score = 75,
                            StudentId = 6,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 27,
                            Score = 65,
                            StudentId = 7,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 28,
                            Score = 82,
                            StudentId = 8,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 29,
                            Score = 63,
                            StudentId = 9,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 30,
                            Score = 75,
                            StudentId = 10,
                            Subject = "Science"
                        });
                });

            modelBuilder.Entity("StudentDataReporting.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "David"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eva"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Frank"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Grace"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hannah"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jack"
                        });
                });

            modelBuilder.Entity("StudentDataReporting.Data.Marks", b =>
                {
                    b.HasOne("StudentDataReporting.Data.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentDataReporting.Data.Student", b =>
                {
                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
